moedas = ['Afegane afegão', 'Ariary malgaxe', 'Baht tailandês', 'Balboa panamenho', 'Birr etíope',
          'Boliviano da Bolívia', 'Bolívar venezuelano', 'Cedi ganês', 'Colom salvadorenho', 'Colón costarriquenho',
          'Coroa dinamarquesa', 'Coroa islandesa', 'Coroa norueguesa', 'Coroa sueca', 'Coroa tcheca',
          'Córdoba nicaraguense', 'Dalasi gambiano', 'Dinar argelino', 'Dinar bareinita', 'Dinar iraquiano',
          'Dinar jordaniano', 'Dinar kuwaitiano', 'Dinar líbio', 'Dinar macedônio', 'Dinar sérvio', 'Dinar tunisiano',
          'Dirham dos Emirados Árabes Unidos', 'Dirham marroquino', 'Dong vietnamita', 'Dram armênio', 'Dólar Liberiano',
          'Dólar americano', 'Dólar australiano', 'Dólar bahamense', 'Dólar barbadense', 'Dólar belizenho',
          'Dólar bermudense', 'Dólar bruneano', 'Dólar canadense', 'Dólar das Ilhas Cayman', 'Dólar das Ilhas Salomão',
          'Dólar de Hong Kong', 'Dólar de Trinidad e Tobago', 'Dólar do Caribe Oriental', 'Dólar fijiano',
          'Dólar guianense', 'Dólar jamaicano', 'Dólar namibiano', 'Dólar neozelandês', 'Dólar singapuriano',
          'Dólar surinamês', 'Escudo cabo-verdiano', 'Euro', 'Florim arubano', 'Florim das Antilhas Holandesas',
          'Florim húngaro', 'Franco CFA Central', 'Franco CFA ocidental', 'Franco CFP', 'Franco burundiano',
          'Franco comoriano', 'Franco congolês', 'Franco do Djibouti', 'Franco guineano', 'Franco ruandês',
          'Franco suíço', 'Gourde haitiano', 'Guarani paraguaio', 'Hryvnia ucraniano', 'Iene japonês', 'Kina papuásia',
          'Kip laosiano', 'Kuna croata', 'Kwacha malauiana', 'Kwacha zambiano', 'Kwanza angolano', 'Lari georgiano',
          'Lek albanês', 'Lempira hondurenha', 'Leone de Serra Leoa', 'Leu moldávio', 'Leu romeno', 'Lev búlgaro',
          'Libra Sudanesa', 'Libra egípcia', 'Libra esterlina', 'Libra libanesa', 'Lilangeni suazi', 'Lira turca',
          'Loti lesotiano', 'Manat azeri', 'Manat turcomano', 'Marco conversível da Bósnia e Herzegovina',
          'Metical moçambicano', 'Naira nigeriana', 'Ngultrum butanês', 'Novo dólar taiwanês', 'Novo shekel israelense',
          'Novo sol peruano', 'Ouguiya mauritana', 'Pataca', 'Paʻanga tonganesa', 'Peso argentino', 'Peso chileno',
          'Peso colombiano', 'Peso cubano', 'Peso dominicano', 'Peso filipino', 'Peso mexicano', 'Peso uruguaio',
          'Pula botsuanesa', 'Quetzal guatemalteco', 'Quiate', 'Rand sul-africano', 'Real brasileiro', 'Remimbi',
          'Rial catariano', 'Rial iemenita', 'Rial iraniano', 'Rial omanense', 'Riel', 'Ringgit malaio', 'Riyal saudita',
          'Rublo bielorrusso', 'Rublo russo', 'Rupia Mauriciana', 'Rupia cingalesa', 'Rupia das Seychelles',
          'Rupia indiana', 'Rupia indonésia', 'Rupia maldívia', 'Rupia nepalesa', 'Rúpia Paquistanesa', 'Som quirguiz',
          'Som uzbeque', 'Somoni', 'Taka bengali', 'Tenge cazaque', 'Unidades de Fomento chilenas', 'Won sul-coreano',
          'Xelim Ugandês', 'Xelim queniano', 'Xelim somali', 'Xelim tanzaniano', 'Yuan chinês (offshore)',
          'Zloty polonês']
